### ISSUE TITLE
MainActivity:setNotifyNextSensor issue

### ISSUE THREAD

**Issue by mbeaty** [devunwired/accessory-samples#1]
Thanks for the code, Dave. Found one small, but consequential bug that prevents your state machine from completing, and resulting in a hung "Enabling Sensors..." progress dialog.

MainActivity:setNotifyNextSensor method, line 324

should break instead of return

**Comment by devunwired** [comment]
Ah, thanks!  Looks like the wrong version got committed.  Fixed.
