### ISSUE TITLE
Legacy BLE and >= SDK 21 BLE

### ISSUE THREAD

**Issue by tpitman** [devunwired/accessory-samples#2]
I have an app that currently works with BLE on < Lollipop devices. When I do the startLeScan with no UUID array it finds my BLE device just fine. If I pass the same service ID for that device into the startLeScan it doesn't find it.

This same thing works fine on a < Lollipop device. Should this work? I am asking you because you have your new Lollipop version of the BLE in your example and thought you would know.

**Comment by devunwired** [comment]
AOSP may be able to help in the matter:
https://android.googlesource.com/platform/frameworks/base/+/android-5.0.2_r1/core/java/android/bluetooth/BluetoothAdapter.java

If you take a look at how they've mapped `startLeScan()` (line ~1656)to used the new APIs underneath, you can see that when an array of UUIDs is passed to the method, they map that into the new `ScanFilter` API. However, it seems they only take the first element, so if you were passing multiple UUIDs before it looks like anything but the first will be dropped.

If you are only passing one UUID, then it should work (and does work in the testing I have done). The callback does also doe a secondary match between detected UUIDs and the original array, so if a mismatch occurs there with the new APIs, the scan results would be dropped as well.

Hope that helps.
