### ISSUE TITLE
Usb accessory Troubleshooting.

### ISSUE THREAD

**Issue by deepakkapoor624** [devunwired/accessory-samples#3]
Hi ,
I am trying to put Nexus 5 in usb accessory Mode using Raspberry Pi . 
I am able to launch the app by using Intent and I am able to communicate with 0 endpoint as it is returning the version of Usb accessory mode i.e 2.0 but I am not able to communicate using bulk endpoint.
Same thing I have done with Motorola phone . I am able to communicate using Bulk endpoint.

**Comment by devunwired** [comment]
Not all devices can support accessory mode and host mode simultaneously. This is up to the device manufacturer.

**Comment by deepakkapoor624** [comment]
But my Nexus 5 is going into Usb accessory Mode as its PID and VID get changes to google accessory PID and VID . Its means I can communicate with control_transfer endpoint but not able to communicate with Bulk end point.
