### ISSUE TITLE
CC2650 SensorTag got error of W/BluetoothGatt: Unhandled exception in callback

### ISSUE THREAD

**Issue by patelvishal1401** [devunwired/accessory-samples#5]
i am using CC2650 SensorTag, Same code of your repo 

01-04 18:19:09.191 24242-24668/com.sencerapp W/BluetoothGatt: Unhandled exception in callback
01-04 18:19:09.191 24242-24668/com.sencerapp W/BluetoothGatt: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.bluetooth.BluetoothGattCharacteristic.getProperties()' on a null object reference
01-04 18:19:09.191 24242-24668/com.sencerapp W/BluetoothGatt:     at android.bluetooth.BluetoothGatt.readCharacteristic(BluetoothGatt.java:882)
01-04 18:19:09.191 24242-24668/com.sencerapp W/BluetoothGatt:     at com.sencerapp.MainActivity$3.readNextSensor(MainActivity.java:352)
01-04 18:19:09.191 24242-24668/com.sencerapp W/BluetoothGatt:     at com.sencerapp.MainActivity$3.onCharacteristicWrite(MainActivity.java:448)
01-04 18:19:09.191 24242-24668/com.sencerapp W/BluetoothGatt:     at android.bluetooth.BluetoothGatt$1.onCharacteristicWrite(BluetoothGatt.java:407)
01-04 18:19:09.191 24242-24668/com.sencerapp W/BluetoothGatt:     at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:279)
01-04 18:19:09.191 24242-24668/com.sencerapp W/BluetoothGatt:     at android.os.Binder.execTransact(Binder.java:453)

**Comment by devunwired** [comment]
Your code does not match mine—line numbers in the stack trace are different for those function calls—indicating you've probably made at least some changes. In order for me to assist you, I would need the full `MainActivity` code from your version.

**Comment by patelvishal1401** [comment]
Yes I make change related with new marshmallow version permission feature but this is not problem 
Your code is support CC2650 SensorTag ?

Here  is my main activity : https://gist.github.com/patelvishal1401/fe467ee60fb8bfbfedf8

**Comment by devunwired** [comment]
Thank you for supplying that, although this code still doesn't match up with the stack trace you've provided. According to this stack trace, line 352 should be a statement inside `readNextSensor()` and line 448 should be a statement inside `onCharacteristiceWrite()`—neither of these are true of the listed code.

Either way, what's happening if that somewhere your code is calling `gatt.readCharacteristic()` from inside `readNextSensor()` with a null parameter. Which usually happens if the UUID is wrong or service discovery failed. But it would be helpful to know WHICH service UUID is causing the failure (since that method is called several times). You might need to add some logging or trace the code to figure out which UUID it is trying to access when null is returned.

The code was written for the original CC2541 SensorTag. I have not tested it on the new version, though according to the docs the UUIDs should all be the same.

**Comment by devunwired** [comment]
I take that back, it seems the new version of the device doesn't include a pressure sensor calibration routine, so the attempts to work with that characteristic ([here](https://gist.github.com/patelvishal1401/fe467ee60fb8bfbfedf8#file-mainactivity-java-L294) and [here](https://gist.github.com/patelvishal1401/fe467ee60fb8bfbfedf8#file-mainactivity-java-L327)) are faulty.

All the UUIDs are still valid, so I'm not quite sure how that manifests itself in the error you've shown me, but it's still incorrect to try and run pressure calibration on the CC2560 version.

The service UUIDs for your device are listed [here](http://processors.wiki.ti.com/index.php/CC2650_SensorTag_User's_Guide#Gatt_Server).

**Comment by patelvishal1401** [comment]
OK , i am trying without pressure sensor

**Comment by patelvishal1401** [comment]
Do you have any idea how we can add more sensor in same code.

This is app for CC2560 : https://github.com/StevenRudenko/BleSensorTag

But it is so complicated for me. i am new with hardware things.

Thats why using you code, its pretty cool and easily understandable.

Let me know if you can help me, i solve problem by removing pressure sensor calibration.

Thanks.. you are excellent.

**Comment by devunwired** [comment]
You just need to discover the UUIDs of the sensor services/characteristics you want to work with an add them. You can find those in the [wiki I linked before](http://processors.wiki.ti.com/index.php/CC2650_SensorTag_User's_Guide#Gatt_Server). Then just include them in the switch statements of the methods just like the existing examples. Each sensor goes through three steps:
1. Enable the sensor (write to the config characteristic)
2. Read the sensor (read from the data characteristic)
3. Enable notifications (write the config descriptor of the data characteristic)

That will enable regular sensor readings to report through `onCharacteristicChanged()` (which will happen roughly once per second using the default update rate.

**Comment by patelvishal1401** [comment]
Hi can you help me how to enable Movement Sensor for Gyroscope, Accelerometer, Magnetometer.
from this link : http://processors.wiki.ti.com/index.php/CC2650_SensorTag_User's_Guide#Gatt_Server

What is      characteristic.setValue(new byte[] { ? });

for each Gyroscope, Accelerometer, Magnetometer.

i tried to much but not getting what to do.

**Comment by devunwired** [comment]
It seems like all the things you are asking about are part of [one sensor](http://processors.wiki.ti.com/index.php/CC2650_SensorTag_User's_Guide#Movement_Sensor). The table on that page describes the bit pattern necessary to enable different parts.

For example: `0x007F` should enable all axes on the gyro, accel, and mag. I can't recall the exact byte order (it think it's LE), so your line of code would look like either:

``` java
characteristic.setValue(new byte[] {(byte)0x7F, (byte)0x00});
```

or

``` java
characteristic.setValue(new byte[] {(byte)0x00, (byte)0x7F});
```

Realize I have no way to test any of this, I'm just extrapolating from the documentation.

**Comment by patelvishal1401** [comment]
Ok, i will test it and let you know!

**Comment by CWallis94** [comment]
Devunwired, I am also trying to use the movement sensors but am unsure if the 

`public static int[] extractCalibrationCoefficients(BluetoothGattCharacteristic c)`

statement is required, and what it's actually for?

**Comment by CWallis94** [comment]
Would anyone please be able to provide the calculations for the movement sensors in Java?
